// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/lordsonvimal/synergy/apps/chess/engine"

func RenderChessPiece(color engine.Color, piece engine.Piece) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if color == engine.White {
			switch piece {
			case engine.Pawn:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "♙")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.Knight:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "♘")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.Bishop:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "♗")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.Rook:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "♖")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.Queen:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "♕")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.King:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "♔")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		} else {
			switch piece {
			case engine.Pawn:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "♟")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.Knight:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "♞")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.Bishop:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "♝")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.Rook:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "♜")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.Queen:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "♛")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			case engine.King:
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "♚")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
