// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func GameInfoPanel() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<aside class=\"w-72 bg-white shadow-lg rounded-xl p-6 flex flex-col gap-6\"><h2 class=\"text-2xl font-bold text-gray-900 border-b pb-2 mb-4\">Game Info</h2><!-- Turn --><div class=\"flex items-center justify-between\"><span class=\"font-semibold text-gray-700\">Turn:</span> <span data-text=\"$sideToMove === 0 ? 'White' : 'Black'\" data-class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(templ.JSExpression(fmt.Sprintf(`
          (() => {
            return {
              'bg-blue-600': $sideToMove === 0,
              'bg-gray-800': $sideToMove === 1,
            };
          })()
			    `)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/components/gameinfopanel.templ`, Line: 20, Col: 10}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"px-3 py-1 rounded-full text-white font-medium\"></span></div><!-- Check --><div class=\"flex items-center justify-between\" data-show=\"$isCheck\" style=\"display: none\"><span class=\"font-semibold text-gray-700\">Check:</span> <span class=\"px-3 py-1 bg-red-600 text-white rounded-full font-semibold\">King in check!</span></div><!-- Game State --><div class=\"flex flex-col\"><span class=\"font-semibold text-gray-700 mb-1\">Game State:</span> <span data-text=\"$gameStateText\" class=\"px-3 py-1 bg-yellow-100 text-yellow-800 rounded-full font-medium\"></span></div><!-- Winner --><div class=\"flex items-center justify-between\" data-show=\"$winner !== 255\" style=\"display: none\"><span class=\"font-semibold text-gray-700\">Winner:</span> <span data-text=\"$winner === 0 ? 'White' : 'Black'\" class=\"px-3 py-1 bg-green-600 text-white rounded-full font-bold\"></span></div></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
