// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ThemeToggle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button id=\"theme-toggle\" type=\"button\" class=\"p-2 rounded-md hover:bg-muted text-ink-secondary transition cursor-pointer focus:outline-none focus:ring-2 focus:ring-primary\" aria-label=\"Toggle dark mode\" onclick=\"toggleTheme()\"><span id=\"theme-icon\"></span></button><script>\n\t\tfunction toggleTheme() {\n\t\t\tconst html = document.documentElement;\n\t\t\tconst current = html.getAttribute(\"data-theme\");\n\t\t\tconst next = current === \"dark\" ? \"light\" : \"dark\";\n\t\t\thtml.setAttribute(\"data-theme\", next);\n\t\t\tlocalStorage.setItem(\"theme\", next);\n\t\t\tupdateThemeIcon(next);\n\t\t}\n\n\t\tfunction updateThemeIcon(theme) {\n\t\t\tconst el = document.getElementById(\"theme-icon\");\n\t\t\tel.textContent = theme === \"dark\" ? \"☀️\" : \"🌙\";\n\t\t}\n\n\t\tupdateThemeIcon(document.documentElement.getAttribute(\"data-theme\") || \"light\");\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
