// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ThemeToggle() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button id=\"theme-toggle\" type=\"button\" class=\"p-2 rounded-md hover:bg-muted text-ink-secondary transition\" aria-label=\"Toggle dark mode\" onclick=\"toggleTheme()\"><svg id=\"theme-icon-light\" class=\"w-5 h-5 hidden\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z\"></path></svg> <svg id=\"theme-icon-dark\" class=\"w-5 h-5 hidden\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z\"></path></svg></button><script>\n\t\tfunction toggleTheme() {\n\t\t\tconst html = document.documentElement;\n\t\t\tconst current = html.getAttribute(\"data-theme\");\n\t\t\tconst next = current === \"dark\" ? \"light\" : \"dark\";\n\t\t\thtml.setAttribute(\"data-theme\", next);\n\t\t\tlocalStorage.setItem(\"theme\", next);\n\t\t\tupdateThemeIcon(next);\n\t\t}\n\n\t\tfunction updateThemeIcon(theme) {\n\t\t\tconst light = document.getElementById(\"theme-icon-light\");\n\t\t\tconst dark = document.getElementById(\"theme-icon-dark\");\n\t\t\tif (theme === \"dark\") {\n\t\t\t\tlight.classList.remove(\"hidden\");\n\t\t\t\tdark.classList.add(\"hidden\");\n\t\t\t} else {\n\t\t\t\tdark.classList.remove(\"hidden\");\n\t\t\t\tlight.classList.add(\"hidden\");\n\t\t\t}\n\t\t}\n\n\t\tupdateThemeIcon(document.documentElement.getAttribute(\"data-theme\") || \"light\");\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
