// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package identity

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func RenderCreateUserWithRelationsForm(
	orgs []OrganizationOption,
	roles []RoleOption,
) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form method=\"post\" action=\"/users/create\" class=\"space-y-6\"><!-- ================= User Info ================= --><section class=\"space-y-4\"><h3 class=\"font-semibold text-lg\">User Details</h3><input type=\"email\" name=\"email\" placeholder=\"Email\" required class=\"w-full rounded border px-3 py-2\"> <input type=\"text\" name=\"name\" placeholder=\"Full name\" required class=\"w-full rounded border px-3 py-2\"> <input type=\"password\" name=\"password\" placeholder=\"Password\" required class=\"w-full rounded border px-3 py-2\"> <label class=\"flex items-center gap-2 text-sm cursor-pointer\"><input type=\"checkbox\" name=\"is_active\" value=\"1\" checked> Active</label></section><!-- ================= Roles ================= --><section class=\"space-y-4\"><h3 class=\"font-semibold text-lg\">Roles</h3><div data-store='{ \"rows\": [ {} ] }' class=\"space-y-3\"><template data-for=\"(row, i) in $rows\"><div class=\"flex gap-2\"><select name=\"roles[][organization_id]\" class=\"flex-1 rounded border px-2 py-1\" required><option value=\"\">Organization</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, org := range orgs {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(org.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `modules/administration/identity/create_user_form.templ`, Line: 57, Col: 30}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(org.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `modules/administration/identity/create_user_form.templ`, Line: 57, Col: 43}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</select> <select name=\"roles[][role_id]\" class=\"flex-1 rounded border px-2 py-1\" required><option value=\"\">Role</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, r := range roles {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(r.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `modules/administration/identity/create_user_form.templ`, Line: 67, Col: 28}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(r.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `modules/administration/identity/create_user_form.templ`, Line: 67, Col: 39}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</select> <button type=\"button\" class=\"px-2 cursor-pointer\" data-on:click=\"$rows.splice(i, 1)\">✕</button></div></template><button type=\"button\" class=\"text-sm text-blue-600 cursor-pointer\" data-on:click=\"$rows.push({})\">+ Add role</button></div></section><!-- ================= Parents / Guardians ================= --><section class=\"space-y-4\"><h3 class=\"font-semibold text-lg\">Parents / Guardians</h3><div data-store='{ \"relations\": [ {} ] }' class=\"space-y-3\"><template data-for=\"(r, i) in $relations\"><div class=\"grid grid-cols-3 gap-2\"><select name=\"relations[][relationship_type]\" class=\"rounded border px-2 py-1 cursor-pointer\" required><option value=\"\">Relation</option> <option value=\"father\">Father</option> <option value=\"mother\">Mother</option> <option value=\"guardian\">Guardian</option></select> <input type=\"email\" name=\"relations[][email]\" placeholder=\"Email\" class=\"rounded border px-2 py-1\"> <input type=\"text\" name=\"relations[][name]\" placeholder=\"Name\" class=\"rounded border px-2 py-1\"></div></template><button type=\"button\" class=\"text-sm text-blue-600 cursor-pointer\" data-on:click=\"$relations.push({})\">+ Add parent / guardian</button></div></section><!-- ================= Submit ================= --><div class=\"flex justify-end gap-2 pt-4\"><button type=\"submit\" class=\"rounded bg-blue-600 px-5 py-2 text-white cursor-pointer\">Create User</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
