// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/lordsonvimal/synergy/apps/chess/ui/components"

func Layout(title string, showBack bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"h-full\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/layouts/layout.templ`, Line: 11, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link rel=\"icon\" type=\"image/svg+xml\" href=\"/favicon.svg\"><link href=\"/static/style.css\" rel=\"stylesheet\"><script>\n\t\t\t\t(function() {\n\t\t\t\t\tconst t = localStorage.getItem(\"theme\");\n\t\t\t\t\tif (t) { document.documentElement.setAttribute(\"data-theme\", t); }\n\t\t\t\t\telse if (window.matchMedia(\"(prefers-color-scheme: dark)\").matches) {\n\t\t\t\t\t\tdocument.documentElement.setAttribute(\"data-theme\", \"dark\");\n\t\t\t\t\t}\n\t\t\t\t})();\n\t\t\t</script></head><body class=\"bg-neutral-50 text-ink h-full flex flex-col\"><header class=\"flex items-center justify-between px-4 py-3 border-b border-edge bg-surface shrink-0\" data-signals.ifmissing='{\"menuOpen\": false}'><div class=\"flex items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if showBack {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"/\" class=\"sm:hidden p-1 rounded-md hover:bg-muted text-ink-secondary transition\" aria-label=\"Back to home\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M15 18l-6-6 6-6\"></path></svg></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a href=\"/\" class=\"flex items-center gap-2 text-lg font-semibold text-ink tracking-tight\"><img src=\"/favicon.svg\" alt=\"ChessLeap logo\" width=\"28\" height=\"28\" class=\"rounded-md\"> ChessLeap</a></div><!-- Desktop nav --><nav class=\"hidden sm:flex items-center gap-1\" aria-label=\"Main navigation\"><a href=\"/\" class=\"px-3 py-1.5 text-sm font-medium text-primary bg-primary-subtle rounded-md\">Play</a> <span class=\"px-3 py-1.5 text-sm font-medium text-ink-dim cursor-not-allowed select-none\" aria-disabled=\"true\" title=\"Coming soon\">Practice</span> <span class=\"px-3 py-1.5 text-sm font-medium text-ink-dim cursor-not-allowed select-none\" aria-disabled=\"true\" title=\"Coming soon\">Class</span></nav><div class=\"flex items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.ThemeToggle().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<!-- Mobile hamburger --><button class=\"sm:hidden p-1.5 rounded-md hover:bg-muted text-ink-secondary transition\" data-on:click=\"$menuOpen = !$menuOpen\" aria-label=\"Toggle navigation menu\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\"></line> <line x1=\"3\" y1=\"12\" x2=\"21\" y2=\"12\"></line> <line x1=\"3\" y1=\"18\" x2=\"21\" y2=\"18\"></line></svg></button></div></header><!-- Mobile dropdown nav --><div class=\"sm:hidden border-b border-edge bg-surface shrink-0\" data-show=\"$menuOpen\" style=\"display:none\"><nav class=\"px-4 py-2 flex flex-col gap-1\" aria-label=\"Mobile navigation\"><a href=\"/\" class=\"px-3 py-2 text-sm font-medium text-primary bg-primary-subtle rounded-md\">Play</a> <span class=\"px-3 py-2 text-sm font-medium text-ink-dim cursor-not-allowed select-none\">Practice <span class=\"text-xs\">(coming soon)</span></span> <span class=\"px-3 py-2 text-sm font-medium text-ink-dim cursor-not-allowed select-none\">Class <span class=\"text-xs\">(coming soon)</span></span></nav></div><main class=\"flex-1 overflow-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</main><div id=\"offline-banner\" class=\"hidden shrink-0 items-center justify-center gap-2 border-t border-warning bg-warning-subtle px-4 py-2 text-sm font-medium text-warning\" role=\"status\" aria-live=\"polite\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"w-4 h-4 shrink-0\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><line x1=\"1\" y1=\"1\" x2=\"23\" y2=\"23\"></line> <path d=\"M16.72 11.06A10.94 10.94 0 0 1 19 12.55\"></path> <path d=\"M5 12.55a10.94 10.94 0 0 1 5.17-2.39\"></path> <path d=\"M10.71 5.05A16 16 0 0 1 22.56 9\"></path> <path d=\"M1.42 9a15.91 15.91 0 0 1 4.7-2.88\"></path> <path d=\"M8.53 16.11a6 6 0 0 1 6.95 0\"></path> <line x1=\"12\" y1=\"20\" x2=\"12.01\" y2=\"20\"></line></svg> No internet connection — changes will not be saved until reconnected</div><script>\n\t\t\t\t(function () {\n\t\t\t\t\tvar banner = document.getElementById('offline-banner');\n\t\t\t\t\tfunction update() {\n\t\t\t\t\t\tbanner.style.display = navigator.onLine ? 'none' : 'flex';\n\t\t\t\t\t}\n\t\t\t\t\twindow.addEventListener('online', update);\n\t\t\t\t\twindow.addEventListener('offline', update);\n\t\t\t\t\tupdate();\n\t\t\t\t})();\n\t\t\t</script><footer class=\"shrink-0 border-t border-edge bg-surface px-4 py-2 flex items-center justify-between\"><span class=\"text-xs text-ink-dim\">ChessLeap</span> <span class=\"text-xs text-ink-dim\">v0.1.0</span></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
