// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html class=\"h-full\"><head><meta charset=\"UTF-8\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `modules/shared/ui/layouts/layout.templ`, Line: 8, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link href=\"/static/style.css\" rel=\"stylesheet\"><script type=\"module\" src=\"https://cdn.jsdelivr.net/gh/starfederation/datastar@1.0.0-RC.7/bundles/datastar.js\"></script></head><body class=\"bg-gray-50 h-full\" data-store='{ \"sidebarOpen\": false }'><div class=\"flex h-full\"><!-- Sidebar --><aside id=\"sidebar\" class=\"fixed md:relative h-full w-64 shrink-0 bg-slate-800 text-slate-100 transform transition-transform duration-200 -translate-x-full md:translate-x-0\" data-class=\"{ 'translate-x-0': $sidebarOpen, '-translate-x-full': !$sidebarOpen }\"><div class=\"flex border-b border-slate-700 items-center justify-between p-4\"><div class=\"text-lg font-bold\">SIS</div><!-- Close button (mobile only) --><button class=\"md:hidden text-xl cursor-pointer\" data-on:click=\"$sidebarOpen = false\" aria-label=\"Close sidebar\">✕</button></div><nav class=\"p-4 space-y-2 text-primary-100\"><a href=\"/\" class=\"block px-4 py-2 rounded hover:bg-slate-600\">Dashboard</a> <a href=\"/organizations\" class=\"block px-4 py-2 rounded hover:bg-slate-600\">Organizations</a> <a href=\"/students\" class=\"block px-4 py-2 rounded hover:bg-slate-600\">Students</a> <a href=\"/courses\" class=\"block px-4 py-2 rounded hover:bg-slate-600\">Courses</a> <a href=\"/fees\" class=\"block px-4 py-2 rounded hover:bg-slate-600\">Fees</a></nav></aside><!-- Main content --><div class=\"flex-1 flex flex-col\"><!-- Top bar (mobile) --><header class=\"md:hidden bg-white shadow p-4 flex items-center\"><button data-on:click=\"$sidebarOpen = !$sidebarOpen\" class=\"mr-4 cursor-pointer\">☰</button><h1 class=\"font-semibold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `modules/shared/ui/layouts/layout.templ`, Line: 73, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</h1></header><!-- Page content --><main class=\"flex-1 overflow-y-auto p-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</main></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
