root = "."
tmp_dir = "tmp/assets"

[build]
  cmd = "templ generate --notify-proxy"
  bin = "/usr/bin/true"
  delay = 100
  include_dir = ["assets"]
  include_ext = ["js", "css"]

[screen]
  clear_on_rebuild = false
